### ISSUE TITLE
Feature request: Re-publish diagnostics after textDocument/didChange

### ISSUE THREAD

**Issue by ttuegel** [josephsumabat/static-ls#120]
The new diff algorithm lets us get adjusted locations for hover/references/etc. after `textDocument/didChange`, but the diagnostic locations are still stale after a file is edited. It would be great if `static-ls` could re-publish the diagnostics after a `didChange` event so they appear in the correct location. (Obviously, the diagnostics themselves may still be out-of-date.)

**Comment by josephsumabat** [comment]
What editor are you using/do you think you could provide a gif of what it currently looks like for you?

Typically the editor handles this directly (I believe on vscode and neovim they should at least)

**Comment by ttuegel** [comment]
I'm using Emacs with Eglot (the built-in LSP client). Thanks for the context; I'll handle the issue on the client side.
