### ISSUE TITLE
Clarification on VSCode Set Up

### ISSUE THREAD

**Issue by theGhostJW** [josephsumabat/static-ls#129]
Hello,
I am having issues getting VSCode to run static-ls and I am confident it is because I'm doing something daft with my VSCode set up.

I have:
1. cloned this repo and built with my version of ghc after bumping a few bounds
2. copied the static-ls binary into a sub-directory in my project
3. made the required changes to package.yaml and recompiled
4. added alloglot VSCode plugin
5. updated workspace settings.json file
6. => now I get the following error when I restart VSCode

```bash
[Error - 10:55:42 PM] alloglot-client-haskell client: couldn``t create connection to server.
Launching server using command static-ls failed. Error: spawn static-ls ENOENT
```

I assume I am not putting `haskell.serverExecutablePath` in the right place?

Here is my `settings.json` 

```json
{
  "languageServerHaskell.useCustomHieWrapper": true,
  "languageServerHaskell.useCustomHieWrapperPath": "hie-wrapper",
  // "haskell.serverExecutablePath": "/workspaces/pyrethrum/staticls/static-ls",
  // "haskell.serverExecutablePath": "static-ls",
  "haskell.serverExecutablePath": "/workspaces/pyrethrum/static-ls",
  "workbench.colorCustomizations": {},
  "cSpell.words": [
    "Aeson",
    "Interactor",
    "Pyrelude"
  ],
  "cSpell.language": "en-GB",
  "cSpell.enabled": true,
  "cSpell.enableFiletypes": [
    "log"
  ],
  "git.closeDiffOnOperation": true,
  "git.postCommitCommand": "push",
  "alloglot.languages":  [
    {
      "languageId": "haskell",
      "serverCommand": "static-ls",
      // "haskell.serverExecutablePath": "/workspaces/pyrethrum/staticls/static-ls",
      // copied to project root - try relative
      // "haskell.serverExecutablePath": "static-ls",
      // try full path
      "haskell.serverExecutablePath": "/workspaces/pyrethrum/static-ls",
    }
  ]
}
```

**Comment by josephsumabat** [comment]
Hi! The `serverCommand` in alloglot is the equivalent to `haskell.serverExecutablePath` from the regular extension (so you should be able to remove `haskell.serverExecutablePath` entirely and instead have `serverCommand` point towards the path to your binary. Let me know if that works for you!

**Comment by theGhostJW** [comment]
OK thanks have raised an MR to tweak the readme. Although i have some other issues now with the server starting I can see from the logs that alloglot is finding the executable
