### ISSUE TITLE
vscode configuration instructions

### ISSUE THREAD

**Issue by codygman** [josephsumabat/static-ls#22]
I think this should be relatively easily supported but I'm not sure how to configure it. haskell/vscode-haskell looks very specific to hls.

**Comment by josephsumabat** [comment]
Actually here's a step by step guide that I'll add to the README when I get a bit more time:

1. Install the Haskell language extension
![image](https://github.com/josephsumabat/static-ls/assets/13813526/cb615eab-6380-4117-b004-0b1db43f897b)

2. Find the Haskell Server Executable option and set it to the path of your static-ls

![image](https://github.com/josephsumabat/static-ls/assets/13813526/ad961817-68dd-4507-9e49-5ddcdb10155a)

(In this case I'm using a nix path but your path might be different)

3. Make sure that you're generating the required static files. Also make sure you have no RTS opts in Vscode, that can cause it to crash!

Let me know if you have any issues or questions, happy to help troubleshoot!

**Comment by codygman** [comment]
Thanks @josephsumabat !

How can you debug null results? I inspected `hiedb` and it appears correct but all lsp requests are null results. Is it a ghc version thing? Is ghc 9.6 not supported perhaps?

**Comment by luis-aparicio** [comment]
> Thanks @josephsumabat !
> 
> How can you debug null results? I inspected `hiedb` and it appears correct but all lsp requests are null results. Is it a ghc version thing? Is ghc 9.6 not supported perhaps?

Here are the logs for the hover and jump to definition: 

`[Debug] <--2-- {"id":2,"jsonrpc":"2.0","result":null}`

`[Debug] <--2-- {"id":5,"jsonrpc":"2.0","result":[]}`

**Comment by josephsumabat** [comment]
Hmm unless there's major differences in the 9.6 and 9.6.1 API 9.6 should be supported - I mainly use it on 9.6.1 so I would expect it to work.

Some common issues:
- If you recently upgraded it's possible your `.hie` files are the wrong version of ghc
- Are the `.hiefiles` directory and `.hiedb` files correctly specified (either in an argument or with the default one?)
- the ghc rts flags option in that plugin can cause it to crash

If you have an open source repo that you're trying it on where it fails I could take a look at that -
I do have an in progress branch which should add better logging options but haven't had time to get it up yet

**Comment by codygman** [comment]
The issue was actually solved by updating to use the latest hiedb version from source in addition to making sure the package.yaml flags in https://github.com/josephsumabat/static-ls#usage all also exist in the cabal variant.

hiedir and one other are missing from the cabal.project version.

**Comment by josephsumabat** [comment]
Oh glad to hear it worked! It was likely the `package.yaml`/cabal flags in that case - it should still work without the --src-base-dir option but that option should slightly improve the accuracy of the file lookups in hiedb!

**Comment by josephsumabat** [comment]
Oh interesting appreciate the report - out of curiosity is your codebase's source code in an `app/`, `src/` or `lib/` directory?

**Comment by codygman** [comment]
We have a few source directories and components but the main one is this in package.yaml:

```yaml
library:
  dependencies:
    base: { version: 4.18.0.0, mixin: [hiding (Prelude)] }
    "ourcustom:prelude": null
  source-dirs:
    - src/lib
```

**Comment by josephsumabat** [comment]
Oh I see -  thanks for the info. I think I know what the issue is.

If you're curious, right now I resolve the directory either by using the hiedb index (which relies on the `--src-base-dir` option or by checking `app/src/lib` for older versions so it's likely that's the reason. I'll see if I can change it to use the cabal configuration at some point.

Thanks for the information!
