### ISSUE TITLE
Consider adding version flag

### ISSUE THREAD

**Issue by austinbutler** [josephsumabat/static-ls#26]
Seems like `static-ls` _can_ work for `nvim-lspconfig`, but by default `:LspInfo` runs the configured language server command + `--version`, then synchronously waits for the result to return. But `static-ls` ignores the `--version` flag and just starts the server, so it never returns. I'm able to work around it with the below configuration, but it might help with compatibility to respond to the `--version` flag with the version. Plus it's just a helpful flag either way.

```lua
	local lspconfig = require("lspconfig")
	lspconfig.hls.setup({
		cmd = { "static-ls" },
		lspinfo = function(cfg)
			return { version = "none" }
		end,
	})
```

**Comment by josephsumabat** [comment]
Thanks! Will throwup a PR

**Comment by josephsumabat** [comment]
https://github.com/josephsumabat/static-ls/pull/29
