### ISSUE TITLE
Consider adding a help command

### ISSUE THREAD

**Issue by chiroptical** [josephsumabat/static-ls#3]
It would be nice to have `--help/-h` to get some information about what I can expect from this.

**Comment by josephsumabat** [comment]
Thanks for the feedback! I'll likely have a wider update to add more arguments in general including `--help` which gives some information but also:

`--hiefilespath <path-to-hiedirectory>` to specify an hie directory (defaulting to .hiefiles)
`--hiedbpath <path-to-hiedb>` to specify an hiedb file

any further suggestions for arguments are also appreciated.
