### ISSUE TITLE
trouble using this with cabal.project

### ISSUE THREAD

**Issue by goolord** [josephsumabat/static-ls#34]
I've tried various configurations but I can't seem to get this to work in projects with more than one cabal package. maybe this has something to do with the workspace being set to the cabal.project file's directory, not sure

**Comment by josephsumabat** [comment]
Ah yeah you're correct I believe that it currently sets the workspace root to the highest level root path where it can find a `cabalproject` and cannot tell when its being used in a sub-project right now.

I believe I should be able to use `getWorkspaceFolders` instead of the `getRootPath` function in the LSP library to fix this. If you have a sample project I'm happy to test it out on that if you like (I should have one that works though).

**Comment by goolord** [comment]
(3) is ideal, i feel like the niche static-ls could easily fill is big megarepos where hls is too fragile to work. 

I'm not familiar enough with hie to understand why this problem requires parsing cabal.project (or whatever) to resolve file names. I would think `hiedb`'s `--src-base-dir` flag would serve to solve this problem. surely there is some information already existing in hiedb that can tell you which directory the indexed .hiefile was generated from

**Comment by josephsumabat** [comment]
>
I'm not familiar enough with hie to understand why this problem requires parsing cabal.project (or whatever) to resolve file names. I would think hiedb's --src-base-dir flag would serve to solve this problem. surely there is some information already existing in hiedb that can tell you which directory the indexed .hiefile was generated from

I did some testing and you're correct - this should work for all definitions/mods indexed with a bit of setup through hiedb. The downside is that you need to individually index each package (though this can be relatively easy to set up with a script relatively easily. Everything except for local definitions which need to have the correct source path pre-pended (I'll likely push up a fix for that).

I was able to get this working by running
```
hiedb -D .hiedb index some-local-package/.hiefiles --src-base-dir some-local-package
```
On a multi-repo code base from the root. (And building the sub-directory individually)/ If you have a sample one that isn't working I'm happy to try it out on that as well.

**Comment by josephsumabat** [comment]
For a general version to index everything:
```
find . -name .hiefiles | awk '{print $1" "substr($1,1,length($1)-length(".hiefiles"))}' | xargs -n2 sh -c 'hiedb -D .hiedb index $0 --src-base-dir=$1 --skip-types'
```

**Comment by josephsumabat** [comment]
Sure if you manage to find one I'm happy to try to get this working on it!

**Comment by josephsumabat** [comment]
No worries! If you're able to mimic it at all I'm happy to help however I can
